[package]
name = "realgeopolitics"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
rand = { version = "0.8", features = ["std"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
