[package]
name = "realgeopolitics-core"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"

[lib]
doctest = false
